mosquitto-conf:
  image: sandinh/mosquitto-conf:1.4.8-2
  labels:
    io.rancher.container.hostname_override: container_name
mosquitto:
  ports:
  - 1883:1883
  image: sandinh/mosquitto:1.4.8-2
  volumes_from:
    - mosquitto-conf
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: mosquitto-conf
