name: Registry Simple
description: |
  Secure Docker registry.  Web based administration.  Optional LDAP authentication.
version: 2.4.1
category: Applications
maintainer: Gia Bao <giabao@sandinh.net>

