.catalog:
  name: "Elasticsearch"
  version: "2.3.3"
  description: "Elasticsearch. You know, for search"
  questions:
    - variable: cluster_name
      description: "Unique name to assign to your Elasticsearch cluster."
      label: "Cluster Name"
      type: "string"
      required: true
      default: "es"
    - variable: kopf_port
      description: "Port for accessing kopf"
      label: "kopf port:"
      type: "int"
      required: true
      default: 80
    - variable: kopf_pw
      description: "kopf basic auth [encrypted password](https://github.com/rancher/catalog-dockerfiles/blob/master/elasticsearch/containers/0.4.0/kopf/README.md#env-variables)"
      label: "kopf password:"
      type: "string"
      required: true

elasticsearch-masters:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        network.host: "_site_"
elasticsearch-datanodes:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
elasticsearch-clients:
  metadata:
    elasticsearch:
      yml:
       cluster.name: "${cluster_name}"
       node.name: "$${HOSTNAME}"
       node.data: "false"
       node.master: "false"
       network.host: "_site_"
