.catalog:
  name: "Registry Simple"
  version: "2.4.1"
  description: "Docker Registry"
  uuid: registry-4
  questions: 
    - variable: "RPORT"
      label: "Registry Port"
      description: "Port on which to run the registry service"
      default: 5000
      required: true
      type: "int"
    - variable: "PPORT"
      label: "Admin Port"
      description: "Port on which to run the frontend administration service"
      default: 443
      required: true
      type: "int"
    - variable: "DIR"
      label: "Storage directory"
      description: "Path of shared storage to use for registry and certificates"
      default: "/registry_dir"
      required: true
      type: "string"
    - variable: "DOMAIN"
      label: "FQDN"
      description: "FQDN of server.  This should be the CN in the certificates and will be the URL to contact the Registry and Web interface"
      required: true
      type: "string"
frontend:
  scale: 1
registry:
  scale: 1
